datalust/superpower

src/Superpower/project.json
Hi,
I've found, that [Superpower](https://www.nuget.org/packages/Superpower/), being one of dependencies of [Serilog.Filters.Expressions](https://github.com/serilog/serilog-filters-expressions), builds only for .NETStandard 1.0. So, I suggest to build it for .NET 4.5 too.
=> Add target .NET Framework 4.5

Superpower.sln, src/Superpower/Superpower.csproj, test/Superpower.Benchmarks/Superpower.Benchmarks.csproj
First attempt at preventing a mass of package references in full-framework projects.
Revs minor version to 1.1.
=> Disable implicit framework references on 4.x

src/Superpower/Combinators.cs, test/Superpower.Tests/Combinators/BetweenCombinatorTests.cs
Added `Between()` combinator allowing to match values, and return the result, between matching a left and a right combinator.
A simple example could e.g. be to match an expression between two parenthesis, such as 
`Expr.Between( Token.EqualTo( Token.LPar ), Token.EqualTo( Token. RPar ) )`
If successful, the result returned is the  result matched by the `Expr` parser.
=> Added Between() combinator

src/Superpower/Model/TokenListParserResult.cs, test/Superpower.Tests/ErrorMessageScenarioTests.cs
Open support for creating an empty `TokenListParserResult`, describing that one in a set of specific tokens were expected.
This method allow consumers to use the internal `Presentation.FormatExpectation`, to create a nice presentation for tokens which are expected.
=> Support for creating an empty result based on expected tokens

src/Superpower/Parse.cs, test/Superpower.Tests/Combinators/ChainCombinatorTests.cs
The current `Parse.Chain()` operator is implemented using recursion. When applied to expressions with moderate size chain of operands and operators, this can cause a stack-overflow.
This pull request changes the implementation of `Parse.Chain()` to an iterative approach, avoiding stack-overflow exceptions.
Attached unit test show how to provoke the stack overflow exception.
=> Chain without recursion

src/Superpower/Model/TextSpan.cs, src/Superpower/Model/TokenizationState.cs, src/Superpower/Parse.cs, src/Superpower/ParserExtensions.cs, src/Superpower/Parsers/Comment.cs, src/Superpower/Parsers/Numerics.cs, src/Superpower/Parsers/Span.cs, src/Superpower/Superpower.csproj, src/Superpower/Tokenizer`1.cs, src/Superpower/Tokenizers/TokenizerBuilder.cs, test/Superpower.Benchmarks/Superpower.Benchmarks.csproj, test/Superpower.Tests/ArithmeticExpressionScenario/ArithmeticExpressionTokenizer.cs, test/Superpower.Tests/ErrorMessageScenarioTests.cs, test/Superpower.Tests/Parsers/NumericsTests.cs, test/Superpower.Tests/Parsers/SpanTests.cs, test/Superpower.Tests/Superpower.Tests.csproj, test/Superpower.Tests/Support/AssertParser.cs, test/Superpower.Tests/Support/PreviousCheckingTokenizer.cs, test/Superpower.Tests/Tokenizer`1Tests.cs, test/Superpower.Tests/Tokenizers/TokenizerBuilderTests.cs
I'm working on this monolithic changeset in an effort to streamline a lot of the tokenization-side of the library. There are breaking changes here that need to be documented before this will be ready to go.
**Edit:**
* Implements #26 - `TokenizerBuilder`
* Fixes #12 - removes `Tokenizer.Previous` - **breaking**
* Accept a sign `+/-` to `Numerics.Integer`, introduces `Numerics.Natural` with the old behavior
* Introduces some new recognizers and parsers
- `Comment.CStyle`, `CPlusPlusStyle`, `SqlStyle`, ShellStyle` and `ToEndOfLine(p)`
- `Span.Regex()`
- `Numerics.IntegerInt64`, `Numerics.Natural*` variants
* Adds `TextSpan.Skip()` and `IsMatch()` extension on text parsers
* `Span.While()` and `Span.Until()` renamed `Span.WithoutAny()` and `Span.WithAll()`, no longer accept zero-length …
=> Initial round of v2 changes

src/Superpower/Combinators.cs, src/Superpower/Parsers/Identifier.cs, src/Superpower/Parsers/Instant.cs, src/Superpower/Parsers/Numerics.cs, src/Superpower/Parsers/QuotedString.cs, src/Superpower/Parsers/Span.cs, test/Superpower.Tests/Parsers/IdentifierTests.cs, test/Superpower.Tests/Parsers/InstantTests.cs, test/Superpower.Tests/Parsers/NumericsTests.cs, test/Superpower.Tests/Parsers/QuotedStringTests.cs, test/Superpower.Tests/Parsers/SpanTests.cs, test/Superpower.Tests/Support/AssertParser.cs
These came out of building the plain text matchers for https://github.com/datalust/seqcli. They're useful for building tokenizers, which we can take advantage of via #26 when it's baked.
Unlike most of the other parsers already in here, they're constructed simply and not fully-optimized. There's a long way to go before we'll have a respectable library of pre-built parsers here, so seems worthwhile to build it out quickly and optimize later.
The ISO-8601 date time parser makes use of regular expression matching, and expects a full date and time component to be present. A good ISO-8601 parser is a mini-project in itself; hopefully this one is a starting point from which we or others can build.
=>  A number of handy additional text parsers

README.md, src/Superpower/Model/Result`1.cs, src/Superpower/Tokenizers/TokenizerBuilder.cs, test/Superpower.Tests/Tokenizers/TokenizerBuilderTests.cs
Deals with this case:
```csharp
[Fact]
public void PartiallyFailedTokenizationIsReported()
{
var tokenizer = new TokenizerBuilder<string>()
.Match(Span.EqualTo("abc"), "abc")
.Match(Span.EqualTo("def"), "def")
.Build();
var tokens = tokenizer.TryTokenize("abd");
Assert.False(tokens.HasValue);
var msg = tokens.ToString();
Assert.Equal("Syntax error (line 1, column 3): unexpected `d`, expected `c`.", msg);
}
```
Previously this would have simply reported _unexpected \`a\`_.
The longest match is used when reporting the error, with top-to-bottom precedent respected.
Also updates the README to show only `TokenizerBuilder` and reference some handwritten examples, since the code that was there is really quite confronting :-)
=> Improve `TokenizerBuilder` error reporting 

sample/DateTimeTextParser/DateTimeParser.csproj, sample/DateTimeTextParser/DateTimeTextParser.cs, sample/DateTimeTextParser/Program.cs, sample/DateTimeTextParser/README.md, src/Superpower/Combinators.cs, test/Superpower.Tests/Combinators/RepeatCombinatorTests.cs
I had a skim through the examples we've got listed in the README, and noticed that the DateTime example had an implementation of `Repeat`, which really belongs in the core library.
The example was a little cluttered with the inclusion of optional `"` double quotes as well as supporting time-only `DateTime`s,, so I've removed those features and hopefully boiled it down to a few core combinators. It's not an optimal implementation, since it should be possible to parse ISO-8601 without allocating, but as an introduction to Superpower it's useful.
=> Repeat combinator

src/Superpower/Combinators.cs, test/Superpower.Tests/Combinators/ApplyCombinatorTests.cs
While working through #32 I couldn't find an idiomatic/allocation-free way for a text parser to break up a number like `20180521` into numeric parts. This led me to a bit of a general pattern, like this:
```csharp
var input = new TextSpan("1234");
var twodigits = Span.Length(2).Apply(Numerics.IntegerInt32);
var result = twodigits(input);
Assert.Equal(12, result.Value);
```
This variant of `Apply()` makes it possible to split the tasks of delimiting the span to be parsed (`Span.Length(2)`) from its translation into the value type (here, taking `12` and parsing an `int`).
Not sure how frequently this will get used - definitely quite pleasant for length-oriented formats like this one - but it's a nice complement to the existing token-oriented `Apply()` combinator, so might prove fruitful …
=> A variant of Apply() that works with any TextParser<TextSpan>

README.md, Superpower.sln, sample/JsonParser/JsonParser.csproj, sample/JsonParser/Program.cs, src/Superpower/Combinators.cs, src/Superpower/Parsers/Character.cs, src/Superpower/Parsers/Numerics.cs, src/Superpower/Tokenizers/TokenizerBuilder.cs, src/Superpower/Util/CharInfo.cs, test/Superpower.Tests/Parsers/SpanTests.cs, test/Superpower.Tests/Tokenizers/TokenizerBuilderTests.cs
We're a bit overdue for a more complete example, I've put together one that parses JSON (a familiar format), while focusing on good error reporting.
It's a runnable program:
```
json> {"foo": [1, 2, {"bar": }]}
Error: Syntax error (line 1, column 24): unexpected `}`, expected JSON value.
json> {"foo": [1, 2, {"bar": 42}]}
Object:
foo
Array:
Number: 1
Number: 2
Object:
bar
Number: 42
```
The whole thing's inline in one long, verbosely-commented `Program.cs` that I've linked from the README.
Was a good opportunity to shake out some small bugs in the process :-)
=> Annotated JSON parser example

sample/JsonParser/Program.cs, src/Superpower/Combinators.cs, src/Superpower/Model/Result`1.cs, src/Superpower/Model/TokenListParserResult.cs, src/Superpower/Model/TokenListParserResult`2.cs, src/Superpower/Model/TokenList`1.cs, src/Superpower/Tokenizers/TokenizerBuilder.cs, test/Superpower.Tests/Combinators/ApplyCombinatorTests.cs, test/Superpower.Tests/Tokenizers/TokenizerBuilderTests.cs
This fixes #37 and makes a number of small improvements; spinning it up via the JSON example :-)...
The number one issue is that `Apply()` should never backtrack if the applied parser fails. Communicating this out to combinators that make these decisions - particularly `Or()` - need to see the `Apply()` parser as having consumed input. This interacts with error location reporting, which makes for some fun juggling of locations, remainders, positions etc.
=> Correctly detect failed Apply() parsers

sample/JsonParser/Program.cs, src/Superpower/Combinators.cs, test/Superpower.Tests/Combinators/ManyDelimitedByCombinatorTests.cs
Thanks for the challenging scenario, @KodrAus :-)
```
json> {x:1}
^
Error: Syntax error (line 1, column 2): unexpected identifier `x`, expected property name or `}`.
json> {"x"]
^
Error: Syntax error (line 1, column 5): unexpected `]`, expected `:`.
json> {"x":}
^
Error: Syntax error (line 1, column 6): unexpected `}`, expected JSON value.
json> {"x":1
^
Error: Syntax error: unexpected end of input, expected `}`.
json> {"x":1,}
^
Error: Syntax error (line 1, column 8): unexpected `}`, expected property name.
json> {"x":1,foo:2}
^
Error: Syntax error (line 1, column 8): unexpected identifier `foo`, expected property name.
json> 
```
The solution to this one was to allow an optional end-delimiter to be passed to `ManyDelimitedBy()`:
```csharp
static TokenListParser<JsonToken, object> …
```
=> Improved terminated-list error reporting by allowing an alternate end delimiter

sample/JsonParser/test.json, src/Superpower/Parsers/Numerics.cs, test/Superpower.Tests/Parsers/NumericsTests.cs
It's a little inconsistent that the integral parsers in `Numerics` have variants that return C# types; this adds `DecimalDecimal` and `DecimalDouble` (it's a little unfortunate that the BCL's naming between integral types like `UInt32` and decimal/floating-point types like `Double` is a little inconsistent :-))
=> Add Numerics.DecimalDecimal and DecimalDouble

src/Superpower/Tokenizers/TokenizerBuilder.cs, test/Superpower.Tests/Tokenizers/TokenizerBuilderTests.cs
This bug results in partial but successful tokenization in some cases where tokenization should fail. Accidental "yield break" where "break" was intended :-)
=> Fix incorrect tokenization when last matcher is delimited

src/Superpower/Model/TextSpan.cs, test/Superpower.Tests/StringSpanTests.cs
The primary purpose of `TextSpan.Equals()` is in comparing remainders when determining whether a parser consumed input. The implementation and doc/intention diverge, this is what _should_ be considered, but we'll have to be on the lookout for parsers broken by this subtle change (shouldn't be many, if any).
Fixes #64.
=> Fix TextSpan.Equals() so that reference equality and length are considered

sample/IntCalc/ArithmeticExpressionTokenizer.cs, src/Superpower/Parsers/Numerics.cs, src/Superpower/Util/CharInfo.cs, test/Superpower.Benchmarks/ArithmeticExpressionScenario/ArithmeticExpressionTokenizer.cs, test/Superpower.Benchmarks/NumberListScenario/NumberListTokenizer.cs, test/Superpower.Tests/ArithmeticExpressionScenario/ArithmeticExpressionTokenizer.cs, test/Superpower.Tests/NumberListScenario/NumberListTokenizer.cs, test/Superpower.Tests/Parsers/NumericsTests.cs, test/Superpower.Tests/SExpressionScenario/SExpressionTokenizer.cs
[`Char.IsDigit`][CharIsDigit] has a very wide, Unicode-based, definition of what's a digit. It returns `true` for digits from the various scripts shown in the table below:
|   0   |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | Script                           |
|:-----:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|---------------------------------|
|   0   |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 | Latin                           |
| 〇/零 | 一 | 二 | 三 | 四 | 五 | 六 | 七 | 八 | 九 | East Asia                       |
|  ο/ō  | Αʹ | Βʹ | Γʹ | Δʹ | Εʹ | Ϛʹ | Ζʹ | Ηʹ | Θʹ | Modern Greek                    |
|       |  א |  ב |  ג |  ד |  ה |  ו |  ז |  ח |  ט | Hebrew                          |
|   ०   |  १ |  २ |  ३ |  ४ |  ५ |  ६ |  ७ |  ८ |  ९ | Devanagari                      |
|   ૦   |  ૧ | …
=> Fix numeric parsers to accept Latin script digits only

src/Superpower/Combinators.cs, test/Superpower.Tests/Combinators/ManyCombinatorTests.cs
Fixes #76.
Many succeeds on partial parsing of an item if backtracking is allowed, but in this case, would report the pre-backtracking remainder in its result.
=> Fixes #76, incorrect remainder used when Many() backtracks

src/Superpower/Display/Presentation.cs, src/Superpower/Model/Result`1.cs, test/Superpower.Tests/Display/PresentationTests.cs
I kept with the switch statement instead of a dictionary so the strings can 'const'd' rather than getting stuck on the heap. If we want to do more than white space naming It could be helpful to pull it out into it's own class with something along the lines of a read-only dictionary interface. 
This is just the general idea.
I'm also wondering if we want to do some kind of naming or "unliterlaization" on the string version, or provide an option.
=>  added character literal translation for the unicode space category

src/Superpower/Parse.cs, test/Superpower.Tests/Combinators/ChainCombinatorTests.cs
As suggested in [issue 81](https://github.com/datalust/superpower/issues/81), this is a built in combinator for situations where a chain of operands (separated by operators) have a different type than the result. This requires an initial seed value for the result and an accumulator function of type Func<TResult, TOperator, TOperand, TResult> .
The Combinator is equivalent to  
from seed in Seed
from chain in (
from operator in Operator
from operand in Operand
select (operator, operand)
).Many()
select  chain.Aggregate(seed, (accu, tuple) => f(accu, tuple.operator, tuple.operand))
One example would be `expr := variable  ( '.' identifier )* ` where a variable alone is a valid expression and variables have nested properties that can be accessed to make a valid expression.
Test coverage is …
=> add chain combinator for left associative operator with a seed

sample/JsonParser/Program.cs
I noticed the tokenizer in the JSON sample would fail to parse strings like `"foo\\"`.
This fixes that by not looking specifically for `\"` but instead ignoring any character preceded by a `\` which ensures it won't be allowed to escape the ending quote if it's another `\`.
=> Fix the JSON parser sample to allow strings ending in '\'.

Superpower.sln.DotSettings, sample/IntCalc/IntCalc.csproj, src/Superpower/Parse.cs, src/Superpower/Superpower.csproj, test/Superpower.Benchmarks/SequencingBenchmark.cs, test/Superpower.Benchmarks/Superpower.Benchmarks.csproj, test/Superpower.Tests/Combinators/BetweenCombinatorTests.cs, test/Superpower.Tests/Combinators/SequenceCombinatorTests.cs, test/Superpower.Tests/Superpower.Tests.csproj, test/Superpower.Tests/Support/AssertParser.cs
`Parse.Sequence()` is a non-allocating alternative to `Then()`. It avoids construction of nested parsers by flattening out the sequence.
A comparison from the benches:
```csharp
static readonly TextParser<(char, char, char)> ThenParser =
Character.Digit.Then(first => 
Character.Digit.Then(second =>
Character.Digit.Then(third => Parse.Return((first, second, third)))));
static readonly TextParser<(char, char, char)> SequenceParser =
Parse.Sequence(
Character.Digit,
Character.Digit,
Character.Digit)
.Select(t => t); // Even up the work done
```
Results from running this on a small input:
|        Method |     Mean |     Error |   StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------- |---------:|----------:|---------:|------:|--------:|-------:|------:|------:|------- …
=> Optimized Parse.Sequence(...) combinator

src/Superpower/Parse.cs, test/Superpower.Tests/Combinators/OneOfCombinatorTests.cs
Implements https://github.com/datalust/superpower/issues/71
=> Added OneOf combinator and tests

src/Superpower/Parsers/Span.cs, test/Superpower.Tests/Parsers/SpanTests.cs
I rely on the compiler to inline functions as necessary, so I have not done any optimizations.
=> Added Span.Until to Superpower.Parsers

Build.ps1, appveyor.yml, global.json, sample/DateTimeTextParser/DateTimeParser.csproj, sample/IntCalc/IntCalc.csproj, sample/JsonParser/JsonParser.csproj, src/Superpower/Superpower.csproj, test/Superpower.Benchmarks/Superpower.Benchmarks.csproj, test/Superpower.Tests/Superpower.Tests.csproj
This updates our SDK target from net5.0 to net6.0, which is the current LTS for .NET.
=> Target net6.0

sample/IntCalc/ArithmeticExpressionToken.cs
=> Fix divide example string

src/Superpower/Model/TextSpan.cs, test/Superpower.Tests/StringSpanTests.cs
This PR adds to `TextSpan`, an indexer, and support for the range operator (`..`)
Exactly how well this is supported depends on the target framework of the application that uses this library:
- .NET Standard 2.1, .NET Core 3, or later: The feature just works (as demonstrated in the unit tests)
- .NET Standard 2.0, or .NET Framework, _with_ a polyfill package such as [IndexRange](https://www.nuget.org/packages/IndexRange) - again, it just works
- .NET Standard 2.0, or .NET Framework, _without_ a polyfill package:  The range operator isn't available, but the indexer and `Slice` methods work as expected.
=> Add index/range support for TextSpan
